interface Resources {
  "translations": {
    "app_title": "مدیکا",
    "app_complete_title": "سامانه ارتباط با مشتری",
    "titles": {
      "dashboard": "پیشخوان",
      "search": "جستجو",
      "not_found": "صفحه یافت نشد",
      "terms_and_conditions": "شرایط و قوانین",
      "privacy": "قوانین و حریم خصوصی",
      "login": "ورود",
      "login_register": "ورود | ثبت نام",
      "notifications": "اطلاعیه ها",
      "add_user": "افزودن کاربر",
      "edit_user": "ویرایش کاربر",
      "users_list": "لیست کاربران",
      "change_role": "تغییر نقش کاربر",
      "401_erorr": "خطای 401",
      "404_erorr": "خطای 404"
    },
    "alert_titles": {
      "shows_row_numbers": "نمایش تعداد ردیف ها",
      "users": "انتخاب کاربر"
    },
    "input_lables": {
      "firstname": "نام",
      "lastname": "نام خانوادگی",
      "username": "نام کاربری",
      "password": "رمز عبور",
      "new_password": "رمز عبور جدید",
      "confirm_password": "تایید رمز عبور",
      "birthdate": "تاریخ تولد",
      "gender": "جنسیت",
      "phone_number": "شماره تلفن",
      "less_than": "کمتر از {{count}}",
      "between_numbers": "بین {{from}} و {{to}}",
      "more_than": "بیشتر از {{count}}",
      "users": "کاربران",
      "verification_code": "کد تایید",
      "current_password": "رمز عبور فعلی",
      "categories": "دسته بندی ها",
      "user_type": "سطح کاربری"
    },
    "inputs": {
      "enter_value": "وارد کنید...",
      "select_value": "انتخاب کنید...",
      "global_search": "عنوان مورد نظر خود را جستجو کنید...",
      "short_search": "جستجو...",
      "username": "نام کاربری خود را وارد کنید...",
      "password": "رمز عبور خود را وارد کنید...",
      "new_password": "رمز عبور جدید خود را وارد کنید...",
      "confirm_password": "رمز عبور خود را  مجدد وارد کنید...",
      "firstname": "نام خود را وارد کنید...",
      "lastname": "نام خانوادگی خود را وارد کنید...",
      "phone_number": "شماره تلفن خود را وارد کنید...",
      "gender": "جنسیت خود را انتخاب کنید...",
      "birthdate": "تاریخ تولد خود را وارد کنید...",
      "users": "کاربر مورد نظر را انتخاب کنید...",
      "user_type": "سطح کاربری را انتخاب کنید...",
      "email": "ایمیل خود را وارد کنید...",
      "upload_avatar": "تصویر مورد نظر خود را آپلود کنید.",
      "categories": "دسته بندی های مورد نظر خود را انتخاب کنید...",
      "discount_percent": "درصد تخفیف را وارد کنید...",
      "start_end_date": "تاریخ شروع و پایان را وارد کنید..."
    },
    "error_res": {
      "not_send_verifycode": "کد تأیید را دریافت نکرده ام!",
      "login_failed": "عملیات ورود با خطا مواجه شد."
    },
    "validations": {
      "email_format": "آدرس ایمیل نامعتبر است.",
      "phone_number_format": "فرمت شماره تلفن نامعتبر است.",
      "number_format": "مقدار وارد شده باید عدد باشد.",
      "requireds": {
        "global": "این فیلد الزامی می باشد.",
        "username": "نام کاربری الزامی می باشد.",
        "email": "ایمیل الزامی می باشد.",
        "password": "رمز عبور الزامی می باشد.",
        "new_password": "رمز عبور جدید الزامی می باشد.",
        "confirm_password": "تایید رمز عبور الزامی می باشد.",
        "firstname": "نام الزامی می باشد.",
        "lastname": "نام خانوادگی الزامی می باشد.",
        "phone_number": "شماره تلفن الزامی می باشد.",
        "gender": "جنسیت الزامی می باشد.",
        "terms_and_conditions": "قبول کردن شرایط و قوانین الزامی می باشد.",
        "birthdate": "تاریخ تولد الزامی می باشد.",
        "user_type": "سطح کاربری الزامی می باشد."
      },
      "minimum": {
        "email": "ایمیل باید 5 کاراکتر یا بیشتر باشد.",
        "password": "رمز عبور باید {{count}} کاراکتر یا بیشتر باشد."
      },
      "maximum": {
        "number_between": "عدد وارد شده باید بین {{from}} تا {{to}} باشد.",
        "password": "رمز عبور باید {{count}} کاراکتر یا کمتر باشد."
      },
      "regex": {
        "password": "حتما یک حرف کوچک / یک حرف بزرگ / دو کاراکتر عددی داشته باشد.",
        "nullable_password": "حتما یک حرف کوچک / یک حرف بزرگ / دو کاراکتر عددی / طول رمز بین 12 تا 30 کاراکتر باشد."
      }
    },
    "buttons": {
      "register": "ثبت نام",
      "search": "جستجو",
      "back_home": "بازگشت به خانه",
      "confirm": "تایید",
      "continue": "ادامه",
      "dismiss": "بستن",
      "back": "بازگشت",
      "activation": "فعالسازی",
      "send_again": "ارسال مجدد",
      "submit": "تایید",
      "close": "بستن",
      "reload": "بارگذاری مجدد",
      "login": "ورود",
      "login_with_phone": "شماره تلفن",
      "login_with_username": "نام کاربری",
      "save": "ذخیره",
      "update_save": "به روزرسانی و ذخیره",
      "loading": "در حال انجام",
      "clear": "پاکسازی",
      "delete": "حذف",
      "delete_all": "حذف همه",
      "excel_export": "خروجی اکسل",
      "row_excel_export": "خروجی اکسل ردیف",
      "view_details": "مشاهده جزئیات",
      "filter": "فیلتر",
      "edit": "ویرایش",
      "add": "اضافه کردن",
      "save_changes": "ذخیره تغییرات",
      "logout": "خروج",
      "read_all": "خواندن همه",
      "change_role": "تغییر نقش کاربر",
      "unassign_role": "اطلاق نقش",
      "unassign_target": "اطلاق هدف",
      "cancel": "لغو",
      "assign_user": "تخصیص کاربر",
      "logout_all_devices": "خروج از همه دستگاه ها",
      "change_password": "تغییر رمز عبور",
      "verification_code_request": "درخواست کد تایید",
      "active": "فعال",
      "deactive": "غیر فعال"
    },
    "checkboxes": {
      "remember_me": "مرا به خاطر بسپار",
      "active": "فعال",
      "deactive": "غیر فعال"
    },
    "messages": {
      "login_welcome": "به سامانه ارتباط با مشتری آی مدیکا خوش آمدید.",
      "loading": "در حال بارگذاری...",
      "loading_by": "در حال بارگذاری {{parameter}}...",
      "adding_sth": "در حال افزودن {{parameter}}...",
      "sending_verification_code": "در حال ارسال پیامک فعالسازی...",
      "changing_password": "در حال تغییر رمز عبور...",
      "loging": "در حال ورود...",
      "deleting": "در حال حذف...",
      "activating": "در حال فعال سازی...",
      "deactivating": "در حال غیر فعال سازی...",
      "data_doesnt_exist": "اطلاعات مورد نظر شما وجود ندارد. مجدد تلاش کنید.",
      "offline_app": "برنامه آماده برای کار آفلاین است.",
      "reload_page": "نسخه جدید در دسترس است، برای به روز رسانی روی دکمه بارگذاری مجدد کلیک کنید.",
      "not_authenticated": "هیچ مجوزی پیدا نشد. این صفحه برای عموم در دسترس نیست.",
      "unread_notification": "شما <NotifCount>{{count}}</NotifCount> اعلان خوانده نشده دارید",
      "unread_notifications": "شما <NotifCount>{{count}}</NotifCount> اعلان خوانده نشده دارید",
      "empty_roles": "هیچ نقشی برای این کاربر انتخاب نشده است.",
      "unauthorized": "نشست شما منقضی شده است. لطفا مجدد وارد شوید.",
      "not_confirm_password": "رمز عبور شما مطابقت ندارد.",
      "disabled_day_after_today": "باید تاریخ های قبل از امروز را انتخاب کنید.",
      "operation_completed_successfully": "عملیات با موفقیت انجام شد.",
      "operation_failed": "عملیات با خطا مواجه شد.",
      "error_404": "اطلاعات مورد نظر شما یافت نشد. مجدد تلاش کنید."
    },
    "choose_lang": {
      "header": "انتخاب زبان"
    },
    "menus": {
      "dashboard": "پیشخوان",
      "user_profile": "پروفایل کاربری"
    },
    "globals": {
      "with": "با",
      "date_format": "روز/ماه/سال",
      "yes": "بله",
      "no": "خیر",
      "time_remaining": "زمان باقیمانده",
      "not_selected": "انتخاب نشده",
      "unknown": "مشخص نشده",
      "woman": "زن",
      "man": "مرد",
      "seconds": "ثانیه",
      "none": "هیچکدام",
      "show": "نمایش",
      "of": "از",
      "go_to_page": "برو به صفحه",
      "page": "صفحه",
      "min": "حداقل",
      "max": "حداکثر",
      "name": "نام",
      "price": "قیمت",
      "actions": "عملیات",
      "row": "ردیف",
      "username": "نام کاربری",
      "user_name": "نام کاربر",
      "progress": "پیشرفت",
      "chart": "نمودار",
      "value": "مقدار",
      "title": "عنوان",
      "type": "نوع",
      "fa_name": "نام فارسی",
      "en_name": "نام انگلیسی",
      "notifications": "اطلاعیه ها",
      "faq": "پرسش و پاسخ ها",
      "all": "همه",
      "unread": "نخوانده ها",
      "new": "جدید",
      "avatar": "تصویر",
      "user_type": "سطح کاربری",
      "fullname": "نام کامل",
      "firstname": "نام",
      "lastname": "نام خانوادگی",
      "email": "ایمیل",
      "birthdate": "تاریخ تولد",
      "phone_number": "شماره تلفن",
      "role": "نقش",
      "gender": "جنسیت",
      "register_date": "تاریخ عضویت",
      "category": "دسته بندی",
      "admin": "مدیر",
      "user": "کاربر",
      "vip_user": "کاربر ارشد",
      "super_admin": "مدیر ارشد",
      "user_roles": "نقش های کاربر",
      "customer": "مشتری",
      "to": "تا",
      "from": "از",
      "selected_dates": "تاریخ های انتخاب شده",
      "date": "تاریخ",
      "start_date": "تاریخ شروع",
      "end_date": "تاریخ پایان",
      "details": "جزئیات",
      "pin_right": "سنجاق به راست",
      "pin_left": "سنجاق به چپ",
      "cancel_pin_right": "خروج از سنجاق به راست",
      "cancel_pin_left": "خروج از سنجاق به چپ",
      "sorting": "مرتب سازی",
      "ascending_sorting": "مرتب سازی صعودی",
      "descending _sorting": "مرتب سازی نزولی",
      "toman": "تومان",
      "rial": "ریال",
      "version": "ورژن",
      "increase": "افزایش",
      "decrease": "کاهش",
      "remaining": "باقی مانده",
      "time": "زمان",
      "sales_count": "تعداد فروش",
      "order_count": "تعداد سفارش",
      "persian_name": "نام فارسی",
      "english_name": "نام انگلیسی",
      "select": "انتخاب",
      "status": "وضعیت",
      "percentage": "درصد"
    }
  }
}

export default Resources;
